use_frameworks!

platform :ios, '9.0'

target 'TestCFrameWork_Example' do
  pod 'TestCFrameWork', :path => '../'

  target 'TestCFrameWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
